export const SYMBOL_NAMES = {
  42: "42-coin",
  BTC: "Bitcoin",
  ETH: "Ethereum",
  USDT: "Tether",
  BNB: "BNB",
  USDC: "USD Coin",
  XRP: "XRP",
  BUSD: "Binance USD",
  ADA: "Cardano",
  DOGE: "Dogecoin",
  MATIC: "Polygon",
  SOL: "Wrapped Solana",
  DOT: "Polkadot",
  SHIB: "Shiba Inu",
  LTC: "Litecoin",
  AVAX: "Avalanche",
  TRX: "TRON",
  DAI: "Dai",
  UNI: "UNICORN Token",
  ATOM: "Cosmos",
  WBTC: "Wrapped Bitcoin",
  LINK: "Chainlink",
  LEO: "UNUS SED LEO",
  ETC: "Ethereum Classic",
  XMR: "Monero",
  TON: "Tokamak Network",
  OKB: "OKB",
  BCH: "Bitcoin Cash",
  APT: "Aptos",
  XLM: "Stellar",
  LDO: "Lido DAO",
  APE: "ApeCoin",
  FIL: "Filecoin",
  CRO: "Cronos",
  ALGO: "Algorand",
  NEAR: "NEAR Protocol",
  HBAR: "Hedera",
  VET: "VeChain",
  QNT: "Quant",
  GRT: "The Graph",
  ICP: "Internet Computer",
  FTM: "Fantom",
  MANA: "Decentraland",
  AAVE: "Aave",
  BIT: "BitRewards",
  EOS: "EOS",
  THETA: "Theta Network",
  FLOW: "Flow",
  EGLD: "MultiversX",
  AXS: "Axie Infinity",
  SAND: "The Sandbox",
  XTZ: "Tezos",
  LUNC: "Terra Classic",
  CHZ: "Chiliz",
  TUSD: "TrueUSD",
  FXS: "Frax Share",
  HT: "Huobi Token",
  USDP: "Pax Dollar",
  KCS: "KuCoin Token",
  BSV: "Bitcoin SV",
  IMX: "ImmutableX",
  CRV: "Curve DAO Token",
  ZEC: "Zcash",
  CAKE: "PancakeSwap",
  MKR: "Maker",
  DASH: "Dash",
  SNX: "Synthetix",
  USDD: "USDD",
  XEC: "eCash",
  OP: "Optimism",
  BTT: "BitTorrent-New",
  MINA: "Mina",
  MIOTA: "IOTA",
  AGIX: "SingularityNET",
  TWT: "Trust Wallet Token",
  NEO: "Neo",
  KLAY: "Klaytn",
  RUNE: "Rune",
  GUSD: "Gemini Dollar",
  GMX: "GMX",
  OSMO: "Osmosis",
  RNDR: "Render Token",
  LRC: "Loopring",
  PAXG: "PAX Gold",
  DYDX: "dYdX",
  ENJ: "Enjin Coin",
  CVX: "Convex Finance",
  GT: "GateToken",
  ZIL: "Zilliqa",
  ETHW: "EthereumPoW",
  CSPR: "Casper",
  "1INCH": "1inch Network",
  FET: "Fetch.ai",
  LUNA: "Terra",
  RPL: "Rocket Pool",
  NEXO: "Nexo",
  BAT: "Basic Attention Token",
  FEI: "Fei USD",
  MAGIC: "MAGIC",
  STX: "Stox",
  HNT: "Helium",
  AR: "Arweave",
  COMP: "Compound",
  KAVA: "Kava",
  WOO: "WOO Network",
  RVN: "Ravencoin",
  HOT: "Hydro Protocol",
  CELO: "Celo",
  XEM: "NEM",
  T: "Threshold",
  XDC: "XDC Network",
  GALA: "Gala",
  ROSE: "Oasis Network",
  ONE: "BigONE Token",
  DCR: "Decred",
  JASMY: "JasmyCoin",
  TFUEL: "Theta Fuel",
  BAL: "Balancer",
  SUSHI: "SushiSwap",
  OCEAN: "Ocean Protocol",
  IOTX: "IoTeX",
  ENS: "Ethereum Name Service",
  GMT: "GMT Token",
  INJ: "Injective",
  WAVES: "Waves",
  GNO: "Gnosis",
  KSM: "Kusama",
  USTC: "TerraClassicUSD",
  QTUM: "Qtum",
  ANKR: "Ankr",
  BONE: "Bone ShibaSwap",
  AUDIO: "Audius",
  SSV: "ssv.network",
  MASK: "Mask Network",
  BTG: "Bitcoin Gold",
  LPT: "Livepeer",
  BNX: "BinaryX",
  YFI: "yearn.finance",
  XCH: "Chia",
  GLMR: "Moonbeam",
  BAND: "Band Protocol",
  FLUX: "Flux",
  KDA: "Kadena",
  JST: "JUST",
  ASTR: "Astar",
  GLM: "Golem",
  XYM: "Symbol",
  XCN: "Cryptonite",
  SC: "Siacoin",
  CHSB: "SwissBorg",
  OMG: "OMG Network",
  ELON: "Dogelon Mars",
  ICX: "ICON",
  ZRX: "0x",
  RSR: "Reserve Rights",
  AMP: "Amp",
  IOST: "IOST",
  HIVE: "Hive",
  ONT: "Ontology",
  BORA: "BORA",
  ILV: "Illuvium",
  BICO: "Biconomy",
  HOOK: "Hooked Protocol",
  WAXP: "WAX",
  STORJ: "Storj",
  KEEP: "Keep Network",
  RLC: "iExec RLC",
  SFP: "SafePal",
  DGB: "DigiByte",
  EVER: "Everscale",
  POLY: "Polymath",
  SXP: "Solar",
  SKL: "SKALE",
  SYN: "Synapse",
  DAO: "DAO Maker",
  METIS: "MetisDAO",
  PEOPLE: "ConstitutionDAO",
  CKB: "Nervos Network",
  UMA: "UMA",
  LSK: "Lisk",
  BTRST: "Braintrust",
  KNC: "Kyber Network Crystal v2",
  CFX: "Conflux",
  NMR: "Numeraire",
  ZEN: "Horizen",
  CEL: "Celsius",
  SLP: "Smooth Love Potion",
  LOOKS: "LooksRare",
  NFT: "APENFT",
  VGX: "Voyager Token",
  MC: "Merit Circle",
  RBN: "Ribbon Finance",
  GAL: "Galatasaray Fan Token",
  PLA: "PlayDapp",
  CELR: "Celer Network",
  HIGH: "Highstreet",
  SYS: "Syscoin",
  GTC: "Game.com",
  CHR: "Chromia",
  MED: "MediBloc",
  API3: "API3",
  HEX: "HEX",
  WTRX: "Wrapped TRON",
  stETH: "Lido Staked ETH",
  TMG: "T-mac DAO",
  GFT: "Gifto",
  WBNB: "Wrapped BNB",
  BTCB: "Bitcoin BEP2",
  FRAX: "Frax",
  HBTC: "Huobi BTC",
  BTTOLD: "BitTorrent",
  FTT: "FTX Token",
  TNC: "TNC Coin",
  XRD: "Radix",
  XAUT: "Tether Gold",
  BabyDoge: "Baby Doge Coin",
  WEMIX: "WEMIX",
  MV: "GensoKishi Metaverse",
  NXM: "NXM",
  BGB: "Bitget Token",
  DFI: "DeFiChain",
  USDJ: "USDJ",
  FLOKI: "FLOKI",
  LN: "LINK",
  ALI: "Artificial Liquid Intelligence",
  LUSD: "Liquity USD",
  EDGT: "Edgecoin",
  BRISE: "Bitgert",
  USDN: "Neutrino USD",
  ANY: "Anyswap",
  WEVER: "Wrapped Everscale",
  LYXe: "LUKSO",
  TEL: "Telcoin",
  LOCUS: "Locus Chain",
  RON: "Ronin",
  BDX: "Beldex",
  CTC: "Creditcoin",
  VVS: "VVS Finance",
  EURS: "STASIS EURO",
  SCRT: "Secret",
  PUNDIX: "Pundi X (New)",
  STG: "Stargate Finance",
  ANT: "Aragon",
  COTI: "COTI",
  CVC: "Civic",
  SNT: "Status",
  TRIBE: "Tribe",
  XNO: "Xeno Token",
  KAS: "Kaspa",
  CTSI: "Cartesi",
  PYR: "Vulcan Forged PYR",
  MNW: "Morpheus.Network",
  POLYX: "Polymesh",
  NU: "NuCypher",
  REQ: "Request",
  MOB: "MobileCoin",
  AXL: "Axelar",
  HFT: "Hashflow",
  ELF: "aelf",
  DEXE: "DeXe",
  CFG: "Centrifuge",
  CEEK: "CEEK VR",
  EWT: "Energy Web Token",
  ONG: "Ontology Gas",
  vUSDC: "Venus USDC",
  SRM: "Serum",
  DENT: "Dent",
  ALPHA: "Alpha Venture DAO",
  RAD: "Radicle",
  MBOX: "MOBOX",
  TRAC: "OriginTrail",
  REN: "Ren",
  ORBS: "Orbs",
  CQT: "Covalent",
  PROM: "Prom",
  AVINOC: "AVINOC",
  DKA: "dKargo",
  ERG: "Ergo",
  SAITAMA: "Saitama",
  HUM: "Humanscape",
  USDX: "USDX [Kava]",
  ARDR: "Ardor",
  MX: "MX TOKEN",
  STEEM: "Steem",
  MVL: "MVL",
  WIN: "WINkLink",
  POWR: "Powerledger",
  ACH: "Alchemy Pay",
  FX: "Function X",
  POND: "Marlin",
  MDX: "Mdex",
  PHA: "Phala Network",
  JOE: "JOE",
  SPELL: "Spell Token",
  NKN: "NKN",
  ACA: "ACA Token",
  REP: "Augur",
  UOS: "Ultra",
  LCX: "LCX",
  RENBTC: "renBTC",
  XPRT: "Persistence",
  XVS: "Venus",
  BFC: "Bifrost",
  XYO: "XYO",
  VOLT: "Bitvolt",
  VRA: "Verasity",
  BSW: "Biswap",
  STRAX: "Stratis",
  RACA: "RACA",
  DESO: "Decentralized Social",
  STPT: "STP",
  MRS: "Metars Genesis",
  MLK: "MiL.k",
  ABBC: "ABBC Coin",
  ZEON: "ZEON",
  MXC: "MXC",
  RBTC: "RSK Smart Bitcoin",
  IQ: "IQ.cash",
  ALICE: "MyNeighborAlice",
  FUN: "FUNToken",
  MTL: "Metal DAO",
  ARRR: "Pirate Chain",
  TLM: "Alien Worlds",
  CTK: "Shentu",
  BNT: "Bancor",
  DAR: "Mines of Dalarnia",
  REEF: "Reef",
  VTHO: "VeThor Token",
  CCD: "Concordium",
  XWC: "WhiteCoin",
  OGN: "Origin Protocol",
  WRX: "WazirX",
  LAT: "PlatON",
  SURE: "inSure DeFi",
  RSS3: "RSS3",
  DODO: "DODO",
  VERI: "Veritaseum",
  QKC: "QuarkChain",
  DEL: "Decimal",
  ORC: "Orbit Chain",
  NEST: "NEST Protocol",
  CTXC: "Cortex",
  OXT: "Orchid",
  EFI: "Efinity Token",
  DUSK: "Dusk Network",
  HI: "HI",
  UQC: "Uquid Coin",
  VLX: "Velas",
  BLOK: "Bloktopia",
  BETA: "Beta Finance",
  SOLO: "Sologenic",
  WMT: "World Mobile Token",
  WVLX: "Wrapped Velas",
  YGG: "Yield Guild Games",
  MAID: "MaidSafeCoin",
  AXEL: "AXEL",
  RIF: "RSK Infrastructure Framework",
  QUACK: "RichQUACK.com",
  STMX: "StormX",
  LQTY: "Liquity",
  DERO: "Dero",
  DAG: "Constellation",
  CORE: "cVault.finance",
  FORTH: "Ampleforth Governance Token",
  AERGO: "Aergo",
  MTRG: "Meter Governance",
  BADGER: "Badger DAO",
  ATA: "Automata Network",
  LOOM: "Loom Network",
  GODS: "Gods Unchained",
  TKO: "Toko Token",
  SUN: "Sun (New)",
  ARK: "Ark",
  AKT: "Akash Network",
  C98: "Coin98",
  META: "Metadium",
  ARPA: "ARPA",
  NOIA: "Syntropy",
  vBUSD: "Venus BUSD",
  TVK: "Virtua",
  DAWN: "Dawn Protocol",
  RAY: "Raydium",
  RARE: "SuperRare",
  SWEAT: "Sweat Economy",
  REV: "Revain",
  MOVR: "Moonriver",
  SUPER: "SuperVerse",
  SUSD: "sUSD",
  SSX: "SOMESING",
  VAI: "VAIOT",
  MBX: "MARBLEX",
  OPUL: "Opulous",
  MBL: "MovieBloc",
  RLY: "Rally",
  RKN: "Rakon",
  SDAO: "SingularityDAO",
  KRD: "Krypton DAO",
  CBK: "Cobak Token",
  STRK: "Strike",
  POLIS: "Polis",
  VEGA: "Vega Protocol",
  AMPL: "Ampleforth",
  LOKA: "League of Kingdoms Arena",
  XVG: "Verge",
  MLN: "Enzyme",
  ETN: "Electroneum",
  UTK: "Utrust",
  MFT: "Hifi Finance (Old)",
  VXV: "Vectorspace AI",
  SFUND: "Seedify.fund",
  WNXM: "Wrapped NXM",
  ankrETH: "Ankr Staked ETH",
  YFII: "DFI.Money",
  PHB: "Phoenix",
  GHST: "Aavegotchi",
  DPI: "DeFi Pulse Index",
  KLV: "Klever",
  COCOS: "Cocos-BCX",
  FLM: "Flamingo",
  SNM: "SONM (BEP-20)",
  XCAD: "XCAD Network",
  QRDO: "Qredo",
  TT: "ThunderCore",
  OUSD: "Origin Dollar",
  COL: "Clash of Lilliput",
  FIS: "StaFi",
  UFO: "UFO Gaming",
  AOG: "AgeOfGods",
  POLS: "Polkastarter",
  BAKE: "BakeryToken",
  PERP: "Perpetual Protocol",
  CBG: "Chainbing",
  XSGD: "XSGD",
  BOBA: "Boba Network",
  ADS: "Adshares",
  ALPACA: "Alpaca Finance",
  WXT: "Wirex Token",
  TLOS: "Telos",
  RAMP: "RAMP",
  CRE: "Carry",
  ONUS: "ONUS",
  WAN: "Wanchain",
  TOMO: "TomoChain",
  CRTS: "Cratos",
  CUSD: "Celo Dollar",
  VIDT: "VIDT DAO",
  LIT: "Lition",
  GZONE: "GameZone",
  GAFI: "GameFi.org",
  MDT: "Measurable Data Token",
  LTO: "LTO Network",
  BWO: "Battle World",
  PRO: "Propy",
  TRU: "TrueFi",
  DEGO: "Dego Finance",
  STARL: "Starlink",
  AGLD: "Adventure Gold",
  BIFI: "BiFi",
  AUCTION: "Bounce Governance Token",
  REI: "REI Network",
  LINA: "Linear Finance",
  LEVER: "LeverFi",
  VRSC: "VerusCoin",
  VOXEL: "Voxies",
  FNCY: "FNCY",
  NVIR: "NvirWorld",
  TIME: "Chrono.tech",
  DFG: "Defigram",
  ATLAS: "Star Atlas",
  BTM: "Bytom",
  DEP: "Depth Token",
  FWT: "Freeway Token",
  FCT: "Factom",
  KMD: "Komodo",
  DIA: "DIA",
  CULT: "Cult DAO",
  IDEX: "IDEX",
  FITFI: "Step App",
  EXRD: "e-Radix",
  WILD: "Wilder World",
  AVA: "Avatly",
  ERN: "Ethernity",
  BOND: "BarnBridge",
  HUNT: "HUNT",
  MCT: "Metacraft",
  BLZ: "Bluzelle",
  DIVI: "Divi",
  ALCX: "Alchemix",
  WOZX: "Efforce",
  MONA: "Monavale",
  KSP: "KLAYswap Protocol",
  KP3R: "Keep3rV1",
  KAI: "KardiaChain",
  AURORA: "Aurora",
  CLV: "CLV",
  NTX: "NuNet",
  CHNG: "Chainge",
  ASD: "ASD",
  DATA: "Streamr",
  QI: "BENQI",
  BTS: "BitShares",
  ORN: "Orion Protocol",
  FORT: "Forta",
  YOOSHI: "YooShi",
  XPR: "Proton",
  MPL: "Maple",
  CON: "CONUN",
  EUROC: "Euro Coin",
  QLC: "Kepple",
  NEBL: "Neblio",
  RARI: "Rarible",
  ALPINE: "Alpine F1 Team Fan Token",
  vUSDT: "Venus USDT",
  GRS: "Groestlcoin",
  PRQ: "PARSIQ",
  HEDG: "HedgeTrade",
  AIOZ: "AIOZ Network",
  TRB: "Tellor",
  SBD: "Steem Dollars",
  ROUTE: "Router Protocol",
  DXD: "DXdao",
  CHESS: "Tranchess",
  BITCI: "Bitcicoin",
  MOC: "Moss Coin",
  NPT: "Neopin",
  HUSD: "HUSD",
  BEL: "Bella Protocol",
  UPP: "Sentinel Protocol",
  EPS: "Ellipsis",
  KILT: "KILT Protocol",
  DC: "Dogechain",
  LAZIO: "S.S. Lazio Fan Token",
  BCD: "Bitcoin Diamond",
  USDK: "USDK",
  AQT: "Alpha Quark Token",
  RFR: "Refereum",
  UNFI: "Unifi Protocol DAO",
  QUICK: "QuickSwap",
  EPX: "Ellipsis",
  XMON: "XMON",
  DNT: "district0x",
  FIO: "FIO Protocol",
  COS: "Contentos",
  CET: "CoinEx Token",
  RSV: "Reserve",
  BAR: "FC Barcelona Fan Token",
  ONIT: "ONBUFF",
  BOSON: "Boson Protocol",
  IRIS: "IRISnet",
  HARD: "Kava Lend",
  TROY: "TROY",
  ICHI: "ICHI",
  NULS: "NULS",
  AE: "Æternity",
  ADX: "Ambire AdEx",
  SOFI: "RAI Finance",
  SPS: "Splintershards",
  GXA: "GALAXIA",
  FIRO: "Firo",
  DERC: "DeRace",
  "": "UGAS",
  vXVS: "Venus XVS",
  UBT: "Unibright",
  TPT: "TokenPocket",
  ELA: "Elastos",
  SANTOS: "Santos FC Fan Token",
  HTR: "Hathor",
  GAS: "Gas",
  SDN: "Shiden Network",
  LON: "Tokenlon Network Token",
  HERO: "Step Hero",
  BURGER: "BurgerCities",
  ASTRAFER: "Astrafer",
  HEGIC: "Hegic",
  PSG: "Paris Saint-Germain Fan Token",
  BZZ: "Swarm",
  OM: "MANTRA",
  VITE: "VITE",
  PIT: "Pitbull",
  SOUL: "Phantasma",
  DBC: "DeepBrain Chain",
  CEUR: "Celo Euro",
  ULT: "Ultiledger",
  KAT: "Kambria",
  WING: "Wing Finance",
  PORTO: "FC Porto Fan Token",
  CREAM: "Cream Finance",
  KRT: "TerraKRW",
  AMB: "AirDAO",
  CITY: "Manchester City Fan Token",
  AHT: "AhaToken",
  VBG: "Vibing",
  RMRK: "RMRK",
  FSN: "Fusion",
  BNANA: "Chimpion",
  COVAL: "Circuits of Value",
  TAMA: "Tamadoge",
  DAFI: "DAFI Protocol",
  DACXI: "Dacxi",
  AION: "Aion",
  TRR: "Terran Coin",
  MARO: "Maro",
  MAP: "MAP Protocol",
  SWAP: "TrustSwap",
  ZBC: "Zebec Protocol",
  GF: "GuildFi",
  FRONT: "Frontier",
  CENNZ: "CENNZnet",
  NAKA: "Nakamoto Games",
  DX: "DxChain Token",
  DG: "Decentral Games",
  BOO: "SpookySwap",
  NMC: "Namecoin",
  DF: "dForce",
  ALEPH: "Aleph.im",
  ORAI: "Oraichain",
  KEY: "SelfKey",
  DEXT: "DEXTools",
  APX: "ApolloX",
  PENDLE: "Pendle",
  DOCK: "Dock",
  BSCPAD: "BSCPAD",
  XTP: "Tap",
  BDP: "BidiPass",
  GYEN: "GYEN",
  HEZ: "Hermez Network",
  FIDA: "Bonfida",
  KUNCI: "Kunci Coin",
  WTC: "Waltonchain",
  KAR: "Karura",
  OOKI: "Ooki Protocol",
  AST: "AirSwap",
  NFTX: "NFTX",
  HSF: "Hillstone Finance",
  CUBE: "Somnium Space Cubes",
  MNGO: "Mango",
  DREP: "Drep [new]",
  PNK: "Kleros",
  PIVX: "PIVX",
  GOC: "GoCrypto Token",
  RFOX: "RFOX",
  CHO: "Choise.com",
  EUM: "Elitium",
  GFI: "Goldfinch",
  PRE: "Presearch",
  ANC: "Anoncoin",
  XHV: "Haven Protocol",
  HYDRA: "Hydra",
  DORA: "Dora Factory",
  LA: "LATOKEN",
  MLT: "MILC Platform",
  SOS: "OpenDAO",
  FOR: "Fortuna Sittard Fan Token",
  BMX: "BitMart Token",
  STRM: "StreamCoin",
  NIM: "Nimiq",
  GEL: "Gelato",
  EGG: "NestEGG Coin",
  AUTO: "Auto",
  PROS: "Prosper",
  PTS: "Petals",
  MEV: "MEVerse",
  SOLVE: "SOLVE",
  MCB: "MUX Protocol",
  WLKN: "Walken",
  ASM: "Assemble Protocol",
  TOKE: "Tokemak",
  APM: "apM Coin",
  NCT: "PolySwarm",
  XFT: "Offshift",
  DAD: "DAD",
  SAITO: "Saito",
  GNY: "GNY",
  SAMO: "Samoyedcoin",
  MET: "Metronome",
  MIM: "Mint Marble",
  YLD: "Yield App",
  CRU: "Crust Network",
  SD: "Stader",
  NSBT: "Neutrino Token",
  HDAO: "HyperDAO",
  BANANA: "ApeSwap",
  AFC: "Arsenal Fan Token",
  MIX: "MixMarvel",
  HNS: "Handshake",
  STC: "Student Coin",
  AKRO: "Akropolis",
  LSS: "Lossless",
  UNCX: "UniCrypt",
  TREEB: "Retreeb",
  SIX: "SIX",
  DVF: "rhino.fi",
  RAINI: "Rainicorn",
  GST: "Green Satoshi Token (SOL)",
  ALU: "Altura",
  HAI: "Hacken Token",
  MATH: "MATH",
  ABT: "Arcblock",
  BIDR: "BIDR",
  DFA: "DeFine",
  GBYTE: "Obyte",
  PDEX: "Polkadex",
  VR: "Victoria VR",
  SCLP: "Scallop",
  FUND: "Unification",
  VBIT: "Valobit",
  WNCG: "Wrapped NCG (Nine Chronicles Gold)",
  FOX: "Shapeshift FOX Token",
  SUKU: "Suku",
  CUDOS: "CUDOS",
  DPR: "Deeper Network",
  HOGE: "Hoge Finance",
  SWTH: "Carbon Protocol",
  BEPRO: "BEPRO Network",
  VINU: "Vita Inu",
  VEED: "VIMworld",
  HOPR: "HOPR",
  ES: "Era Swap",
  PKF: "Firebird",
  IMPT: "IMPT",
  ALT: "Alitas",
  AMO: "AMO Coin",
  MAN: "Matrix AI Network",
  MITX: "Morpheus Labs",
  CVP: "PowerPool",
  CRPT: "Crypterium",
  MSOL: "Marinade Staked SOL",
  WRLD: "NFT Worlds",
  URUS: "Aurox",
  WABI: "Wabi",
  KAN: "BitKan",
  CERE: "Cere Network",
  HAPI: "HAPI Protocol",
  XED: "Exeedme",
  ZNN: "Zenon",
  SWASH: "Swash",
  ZKS: "ZKSpace",
  RISE: "Rise",
  VELO: "Velodrome Finance",
  LBC: "LBRY Credits",
  BOA: "BOSagora",
  ACM: "Actinium",
  MVC: "MileVerse",
  DDX: "DerivaDAO",
  MASQ: "MASQ",
  TABOO: "TABOO TOKEN",
  KRL: "Kryll",
  UFT: "UniLend",
  SERO: "Super Zero Protocol",
  TTT: "The Transfer Token",
  GOVI: "Govi",
  PART: "Particl",
  QSP: "Quantstamp",
  VTC: "Vertcoin",
  AURY: "Aurory",
  ADP: "Adappter Token",
  SLND: "Solend",
  BTSE: "BTSE",
  OAX: "OAX",
  PPC: "Peercoin",
  CAJ: "Cajutel",
  BASIC: "BASIC",
  EL: "ELYSIA",
  VAL: "SORA Validator Token",
  NUM: "Numbers Protocol",
  RED: "RED TOKEN",
  BTCST: "Bitcoin Standard Hashrate Token",
  ATM: "Atletico De Madrid Fan Token",
  BOTTO: "Botto",
  GARI: "Gari Network",
  APL: "Apollon Limassol",
  DVI: "Dvision Network",
  ERC20: "ERC20",
  BIOT: "BioPassport Token",
  CAPS: "Ternoa",
  KIN: "Kin",
  PERL: "PERL.eco",
  BEND: "BendDAO",
  VRT: "Venus Reward Token",
  JUV: "Juventus Fan Token",
  OG: "OG Fan Token",
  TOWN: "Town Star",
  STOS: "Stratos",
  SOCKS: "Unisocks",
  BABY: "BabySwap",
  OXEN: "Oxen",
  RAVEN: "Raven Protocol",
  KOK: "KOK",
  PUSH: "Push Protocol",
  IHF: "Invictus Hyperion Fund",
  BNC: "Bifrost",
  CLO: "Callisto Network",
  POOLZ: "Poolz Finance",
  QTCON: "Quiztok",
  TONE: "TE-FOOD",
  XDEFI: "XDEFI Wallet",
  SHPING: "SHPING",
  WICC: "WaykiChain",
  PTU: "Pintu Token",
  MCRT: "MagicCraft",
  ROOK: "Rook",
  DLC: "Dollarcoin",
  MANC: "Mancium",
  INTER: "Inter Milan Fan Token",
  CTX: "Cryptex Finance",
  QRL: "Quantum Resistant Ledger",
  MWC: "MimbleWimbleCoin",
  MOOV: "Dotmoovs",
  PKT: "Playkey",
  LTX: "Lattice Token",
  EPIK: "EPIK Prime",
  XDB: "DigitalBits",
  CIV: "Civitas",
  RDD: "ReddCoin",
  NWC: "Newscrypto",
  PZM: "PRIZM",
  GO: "GoChain",
  IDRT: "Rupiah Token",
  OBSR: "Observer",
  FRA: "Findora",
  WHALE: "WHALE",
  AGRS: "Agoras: Currency of Tau",
  NAP: "Napoli Fan Token",
  DMD: "Diamond",
  BAN: "Banano",
  XNC: "XeniosCoin",
  vLTC: "Venus LTC",
  ZCN: "Zus",
  PNG: "Pangolin",
  SOV: "Sovryn",
  RAE: "Receive Access Ecosystem",
  PALLA: "Pallapay",
  BRG: "Bridge Oracle",
  VEE: "BLOCKv",
  NYE: "NewYork Exchange",
  GRID: "Grid+",
  CELL: "Cellframe",
  AVT: "Aventus",
  BTRS: "Bitball Treasure",
  DVPN: "Sentinel",
  DIME: "Dimecoin",
  XRT: "Robonomics.network",
  ACX: "Across Protocol",
  TORN: "Tornado Cash",
  PEEL: "Meta Apes",
  SPA: "Sperax",
  XOR: "SORA",
  SIDUS: "SIDUS",
  RING: "Darwinia Network",
  OVR: "OVR",
  SHR: "ShareToken",
  DGD: "DigixDAO",
  EMRX: "Emirex Token",
  THG: "Thetan Arena",
  TEMCO: "TEMCO",
  BUY: "Buying.com",
  WOM: "Wombat Exchange",
  XMC: "Monero Classic",
  SFD: "SAFE DEAL",
  CTI: "ClinTex CTi",
  BTC2: "Bitcoin 2",
  HELLO: "HELLO",
  ZYN: "Zynecoin",
  IHC: "Inflation Hedging Coin",
  QASH: "QASH",
  PSTAKE: "pSTAKE Finance",
  NFTB: "NFTb",
  TITAN: "TitanSwap",
  ZANO: "Zano",
  IPAD: "Infinity PAD",
  BCN: "Bytecoin",
  ASTA: "ASTA",
  XCP: "Counterparty",
  NXS: "Nexus",
  ARIA20: "Arianee",
  ASR: "AS Roma Fan Token",
  FAB: "Fabric",
  IGNIS: "Ignis",
  STFX: "STFX",
  UPUNK: "Unicly CryptoPunks Collection",
  SHILL: "SHILL Token",
  CBX: "CropBytes",
  HIBS: "Hiblocks",
  EQUAD: "QuadrantProtocol",
  DYP: "Dypius",
  EPIC: "Epic Cash",
  FRTS: "Fruits",
  ROOBEE: "ROOBEE",
  BUX: "BUX Token",
  MOF: "Molecular Future",
  LOVELY: "Lovely Inu Finance",
  INV: "Inverse Finance",
  BTR: "Bitether",
  EFX: "Effect Network",
  XEP: "Electra Protocol",
  ASK: "Permission Coin",
  AWC: "Atomic Wallet Coin",
  PCX: "ChainX",
  SYLO: "Sylo",
  BOLT: "BOLT",
  POSI: "Position Exchange",
  KROM: "Kromatika",
  SWFTC: "SwftCoin",
  EVZ: "Electric Vehicle Zone",
  GLCH: "Glitch",
  GULF: "Gulf Coin",
  JUP: "Jupiter",
  vDAI: "Venus DAI",
  GHX: "GamerCoin",
  XPX: "ProximaX",
  PROB: "ProBit Token",
  BEAM: "Beam",
  CIRUS: "Cirus Foundation",
  JGN: "Juggernaut",
  POLK: "Polkamarkets",
  PTP: "Platypus Finance",
  ITGR: "Integral",
  SHIRYO: "Shiryo",
  GLQ: "Graphlinq Protocol",
  SCP: "ScPrime",
  CAS: "Cashaa",
  BF: "BitForex Token",
  PEAK: "PEAKDEFI",
  CRP: "Crypton",
  HC: "HyperCash",
  RUSH: "RUSH COIN",
  TRVL: "TRVL",
  TRA: "Trabzonspor Fan Token",
  FUSE: "Fuse Network",
  DRGN: "Dragonchain",
  DOBO: "DogeBonk",
  FST: "1irstcoin",
  MEETONE: "MEET.ONE",
  CARD: "Cardstack",
  ZASH: "ZIMBOCASH",
  SFI: "saffron.finance",
  STAKE: "STAKE",
  UNO: "Uno Re",
  XCV: "XCarnival",
  NXT: "Nxt",
  BLP: "BullPerks",
  TRIAS: "Trias Token (new)",
  MBS: "MonkeyLeague",
  CMP: "Caduceus",
  LITH: "Lithium",
  HAM: "Hamster",
  NAV: "Navcoin",
  MITH: "Mithril",
  GOM2: "AnimalGo",
  vLINK: "Venus LINK",
  WIKEN: "Project WITH",
  NOW: "ChangeNOW Token",
  PI: "Plian",
  NEER: "Metaverse.Network Pioneer",
  VID: "Vivid Labs",
  VALOR: "Valor Token",
  DIP: "Etherisc DIP Token",
  RVF: "RocketX exchange",
  TRV: "TrustVerse",
  MINTME: "MintMe.com Coin",
  DNA: "Metaverse Dualchain Network Architecture",
  GENE: "Genopets",
  AZIT: "Azit",
  PAY: "TenX",
  VSP: "Vesper",
  ISP: "Ispolink",
  SHX: "Stronghold Token",
  STACK: "StackOs",
  PEX: "PosEx",
  WOOP: "Woonkly Power",
  O3: "O3 Swap",
  BITCNY: "bitCNY",
  VSYS: "v.systems",
  NEW: "Newton",
  NEX: "Nash",
  CUMMIES: "CumRocket",
  MONI: "Monsta Infinite",
  VEMP: "VEMP",
  REVV: "REVV",
  TARA: "Taraxa",
  KARMA: "KARMA",
  SAN: "Santiment Network Token",
  OGV: "Origin Dollar Governance",
  MOBI: "Mobius",
  BHP: "BHPCoin",
  ABYSS: "Abyss",
  RVLT: "Revolt 2 Earn",
  TAROT: "Tarot",
  SALT: "SALT",
  DHT: "dHedge DAO",
  BIP: "Minter Network",
  GRC: "Gridcoin",
  SAFEMOON: "SafeMoon",
  CHI: "Xaya",
  NVT: "NerveNetwork",
  ENQ: "Enecuum",
  ILC: "ILCOIN",
  DSLA: "DSLA Protocol",
  IDLE: "Idle",
  BAAS: "BaaSid",
  SMT: "Swarm Markets",
  ETHPAD: "ETHPad",
  ALBT: "AllianceBlock",
  XTM: "Torum",
  HOD: "HoDooi.com",
  INSUR: "InsurAce",
  CGT: "CACHE Gold",
  TOMS: "TomTomCoin",
  FB: "Fenerbahçe Token",
  MINT: "Public Mint",
  STRX: "StrikeX",
  MTH: "Monetha",
  DFL: "DeFi Land",
  SLRS: "Solrise Finance",
  PPT: "Populous",
  CARBON: "Carboncoin",
  GEEQ: "Geeq",
  DTEP: "DECOIN",
  KYL: "Kylin",
  HORD: "Hord",
  SKEY: "Skey Network",
  MANDOX: "MandoX V2",
  BFT: "Brazil National Football Team Fan Token",
  THN: "Throne",
  RTH: "Rotharium",
  XFC: "Footballcoin (XFC)",
  eRSDL: "unFederalReserve",
  KONO: "Konomi Network",
  BETU: "BetU",
  SWRV: "Swerve",
  COLX: "ColossusXT",
  ZOO: "ZooKeeper",
  PSP: "ParaSwap",
  MHC: "#MetaHash",
  MAPS: "MAPS",
  LGCY: "LGCY Network",
  RAZOR: "Razor Network",
  NFTART: "NFT Art Finance",
  LCC: "Litecoin Cash",
  ZIG: "Zigcoin",
  LIKE: "Only1",
  KALM: "KALM",
  SFT: "Safex Token",
  AIRI: "aiRight",
  LIME: "iMe Lab",
  NBT: "NanoByte Token",
  SEELE: "Seele-N",
  AART: "ALL.ART protocol",
  SAFE: "SafeCoin",
  STRP: "Strips Finance",
  VEST: "VestChain",
  KMON: "Kryptomon",
  TAU: "Lamden",
  CARE: "Carebit",
  PXP: "PointPay",
  LIFE: "Life Crypto",
  IDV: "Idavoll DAO",
  SATA: "Signata",
  LYM: "Lympo",
  ERA: "Era Token (Era7)",
  LAND: "Landbox",
  SENATE: "SENATE",
  PMON: "Polychain Monsters",
  TXA: "Project TXA",
  EOSDT: "EOSDT",
  ROCO: "ROCO FINANCE",
  VCF: "Valencia CF Fan Token",
  SIB: "SIBCoin",
  PAC: "PAC Protocol",
  SNTVT: "Sentivate",
  JOB: "Jobchain",
  ICE: "Decentral Games ICE",
  PMGT: "Perth Mint Gold Token",
  FINA: "Defina Finance",
  DIGG: "DIGG",
  PRIMATE: "Primate",
  TNB: "Time New Bank",
  NORD: "Nord Finance",
  FREE: "FREEdom Coin",
  ERTHA: "Ertha",
  UNB: "Unbound",
  ANW: "Anchor Neural World",
  "1ART": "OneArt",
  SHA: "Safe Haven",
  GPX: "GPEX",
  MFG: "Smart MFG",
  NAS: "Nebulas",
  FWC: "Football World Community",
  DAX: "DAEX",
  TRUE: "TrueChain",
  LAYER: "UniLayer",
  DOGGY: "DOGGY",
  GRIMM: "Grimm",
  HZN: "Horizon Protocol",
  UBX: "UBIX.Network",
  WSG: "Wall Street Games",
  APIX: "APIX",
  EDG: "Edgeless",
  FLX: "Reflexer Ungovernance Token",
  PLAY: "HEROcoin",
  BRKL: "Brokoli Network",
  ZLW: "Zelwin",
  ETP: "Metaverse ETP",
  TRAVA: "TRAVA.FINANCE",
  PING: "Sonar",
  EOSC: "EOS Force",
  MSB: "Misbloc",
  ARDX: "ArdCoin",
  ATT: "Attila",
  RDN: "Raiden Network Token",
  OMC: "Ormeus Cash",
  MTA: "mStable Governance Token: Meta (MTA)",
  CONV: "Convergence",
  PIAS: "PIAS",
  BTCP: "Bitcoin Private",
  "0xBTC": "0xBitcoin",
  RPG: "Revolve Games",
  DINGO: "DINGO TOKEN (old)",
  TRADE: "Unitrade",
  KOM: "Kommunitas",
  SMI: "SafeMoon Inu",
  COMBO: "Furucombo",
  BTCZ: "BitcoinZ",
  DPET: "My DeFi Pet",
  BLANK: "BlockWallet",
  XBY: "XTRABYTES",
  KRIPTO: "Kripto koin",
  VXL: "Voxel X Network",
  TENT: "TENT",
  SWP: "Kava Swap",
  GMD: "The Coop Network",
  OLE: "OpenLeverage",
  PORNROCKET: "PornRocket",
  AEON: "Aeon",
  UMB: "Umbrella Network",
  PRT: "Portion",
  PLANETS: "PlanetWatch",
  HAWK: "Hawksight",
  TCT: "TokenClub",
  XLT: "Nexalt",
  ACK: "AcknoLedger",
  IQN: "IQeon",
  CS: "Credits",
  MARSH: "UnMarshal",
  TOP: "TOP",
  METAPETS: "MetaPets",
  CRON: "Cryptocean",
  ACE: "ACENT",
  YAXIS: "yAxis",
  STAK: "STRAKS",
  WGR: "Wagerr",
  SN: "SpaceN",
  IMT: "Moneytoken",
  VEX: "Vexanium",
  DEC: "Decentr",
  EBEN: "Green Ben",
  MOVEZ: "MOVEZ",
  VIA: "Viacoin",
  ACCEL: "ACCEL",
  BCMC: "Blockchain Monster Hunt",
  STANDARD: "Stakeborg DAO",
  RYOSHI: "Ryoshi Token",
  "8PAY": "8PAY",
  HEC: "Heroes Chained",
  REVO: "Revomon",
  XFL: "Florin",
  RHYTHM: "Rhythm",
  PPAY: "Plasma Finance",
  STBU: "Stobox Token",
  EXRN: "EXRNchain",
  MEME: "Memeverse",
  MIR: "MIR COIN",
  ALY: "ALLY",
  MSU: "MetaSoccer",
  EM: "Eminer",
  AME: "AME Chain",
  KINGSHIB: "King Shiba",
  ZMN: "ZMINE",
  GTH: "Gather",
  VAB: "Vabble",
  BTX: "BitCore",
  STARS: "Mogul Productions",
  DPS: "DEEPSPACE",
  GMB: "GAMB",
  IOI: "IOI Token",
  FO: "FIBOS",
  TKP: "TOKPIE",
  WNT: "Wicrypt",
  GMPD: "GamesPad",
  CMERGE: "CoinMerge (ERC-20)",
  XRUNE: "Thorstarter",
  DRF: "DRIFE",
  ISIKC: "Isiklar Coin",
  HANDY: "Handy",
  LABS: "LABS Group",
  METAX: "MetaverseX",
  FAIR: "FairGame",
  XBC: "Bitcoin Plus",
  MTC: "DOC.COM",
  DTA: "DATA",
  GIO: "Graviocoin",
  TFBX: "TrueFeedBack",
  BIN: "Binemon",
  SCCP: "S.C. Corinthians Fan Token",
  TXL: "Autobahn Network",
  ODDZ: "Oddz",
  OPEN: "Open Platform",
  PBX: "Paribus",
  FCD: "FreshCut Diamond",
  BLK: "BlackCoin",
  PKR: "Polker",
  HPB: "High Performance Blockchain",
  CMT: "Comet",
  TMTG: "The Midas Touch Gold",
  INT: "INT",
  SMARTCREDIT: "SmartCredit Token",
  SRN: "SIRIN LABS Token",
  OK: "Okcash",
  DTX: "Databroker",
  AMLT: "AMLT",
  KCCPAD: "KCCPAD",
  C20: "CRYPTO20",
  DIO: "Decimated",
  BMP: "Brother Music Platform",
  SUMO: "Sumokoin",
  HOTCROSS: "Hot Cross",
  SWOP: "Swop",
  MDA: "Moeda Loyalty Points",
  RAZE: "Raze Network",
  HAND: "ShowHand",
  XHI: "HiCoin",
  CHAT: "ChatCoin",
  DDD: "Scry.info",
  YEC: "Ycash",
  BP: "Beyond Protocol",
  LUFC: "Leeds United Fan Token",
  FEVR: "RealFevr",
  BLOCK: "Blocknet",
  YAE: "Cryptonovae",
  FARA: "FaraLand",
  IETH: "iEthereum",
  PNY: "Peony",
  VIN: "VINchain",
  YOYOW: "YOYOW",
  EDEN: "Eden",
  BHC: "Billion Happiness",
  DRM: "Dreamcoin",
  SHIBX: "SHIBAVAX",
  SLICE: "Tranche Finance",
  WHITE: "Whiteheart",
  ESD: "Empty Set Dollar",
  KAMPAY: "KamPay",
  LOCG: "LOCGame",
  SHI: "Shirtum",
  LET: "LinkEye",
  HYVE: "Hyve",
  YOU: "YOU COIN",
  PLSPAD: "PulsePad",
  SYNC: "SYNC Network",
  WOOF: "WoofWork.io",
  CCX: "Conceal",
  LEDU: "Education Ecosystem",
  WELT: "Fabwelt",
  POA: "POA Network",
  AZY: "Amazy",
  DOUGH: "PieDAO DOUGH v2",
  BMI: "Bridge Mutual",
  TFT: "ThreeFold",
  STRONG: "Strong",
  VPP: "Virtue Poker",
  AIT: "AICHAIN",
  SKILL: "CryptoBlades",
  MRX: "Metrix Coin",
  LKR: "Lokr",
  ORS: "Origin Sport",
  IGG: "IG Gold",
  MAX: "MAX Exchange Token",
  BIRD: "Birdchain",
  KICK: "KickToken",
  BTO: "Bottos",
  GVT: "Genesis Vision",
  ONSTON: "ONSTON",
  APPC: "AppCoins",
  NAFT: "Nafter",
  RCN: "Ripio Credit Network",
  BLAST: "SafeBlast",
  URQA: "UREEQA",
  HUSH: "Hush",
  PST: "Primas",
  CYC: "Cyclone Protocol",
  BGL: "Bitgesell",
  BOB: "BOB",
  CLEG: "Chain of Legends",
  SAUBER: "Alfa Romeo Racing ORLEN Fan Token",
  ATL: "ATLANT",
  MPH: "88mph",
  BITB: "Bean Cash",
  AGA: "AGA Token",
  GSC: "Global Social Chain",
  LINKA: "LINKA",
  UPI: "Pawtocol",
  PUMLX: "PUMLx",
  CRBN: "Carbon",
  RIO: "Realio Network",
  HGOLD: "HollyGold",
  LXT: "Litex",
  XPD: "PetroDollar",
  NFTY: "NFTY Token",
  S4F: "S4FE",
  NYC: "NewYorkCoin",
  CPO: "Cryptopolis",
  TONS: "Thisoption",
  PUT: "PUTinCoin",
  XY: "XY Finance",
  FRKT: "FRAKT Token",
  XPC: "eXPerience Chain",
  VIBE: "VIBE",
  CAT: "Cat Token",
  UMASK: "Unicly Hashmasks Collection",
  KCASH: "Kcash",
  HVN: "Hiveterminal Token",
  KEX: "Kira Network",
  MTN: "Medicalchain",
  BBANK: "blockbank",
  JAR: "Jarvis+",
  EUNO: "EUNO",
  HIT: "HitChain",
  ZOON: "CryptoZoon",
  UFR: "Upfiring",
  KABY: "Kaby Arena",
  RYO: "Ryo Currency",
  FLP: "FLIP",
  TIPS: "FedoraCoin",
  CORN: "Cornichon",
  TUP: "TenUp",
  EFC: "Everton Fan Token",
  BOLLY: "BollyCoin",
  ORB: "Orbitcoin",
  HTDF: "Orient Walt",
  WATCH: "yieldwatch",
  XMV: "MoneroV",
  SPO: "Spores Network",
  CNTR: "Centaur",
  XCUR: "Curate",
  DAPS: "DAPS Coin",
  FS: "FantomStarter",
  RBLX: "Rublix",
  XLA: "Scala",
  OPIUM: "Opium",
  NBOT: "Naka Bodhi Token",
  ELMON: "Elemon",
  UCH: "Universidad de Chile Fan Token",
  RAID: "Ancient Raid",
  SPFC: "Sao Paulo FC Fan Token",
  FTG: "OnGo",
  STA: "STATERA",
  PWAR: "PolkaWar",
  CORA: "Corra.Finance",
  PMA: "PumaPay",
  PTOY: "Patientory",
  IXC: "Ixcoin",
  OCN: "Odyssey",
  KGO: "KIWIGO",
  HAKKA: "Hakka.Finance",
  NAX: "NextDAO",
  FEX: "FidexToken",
  BMON: "Binamon",
  TRL: "Triall",
  BHD: "BitcoinHD",
  D: "Denarius",
  PLOT: "PlotX",
  CRWNY: "Crowny",
  MIN: "Minswap",
  DAPP: "LiquidApps",
  PTF: "PowerTrade Fuel",
  STM: "Streamity",
  FYP: "FlypMe",
  KRB: "Karbo",
  NCDT: "Nuco.cloud",
  XDN: "DigitalNote",
  XCASH: "X-CASH",
  GCOIN: "Galaxy Fight Club",
  TOK: "Tokenplace",
  CSP: "Caspian",
  SMLY: "SmileyCoin",
  FYD: "FYDcoin",
  GTON: "GTONCapital",
  RUFF: "Ruff",
  CURE: "Curecoin",
  UMX: "UniMex Network",
  IF: "Impossible Finance",
  HYPE: "Supreme Finance",
  DAPPX: "dAppstore",
  EVRY: "EVRYNET",
  GHNY: "Grizzly Honey",
  vBCH: "Venus BCH",
  BASE: "Base Protocol",
  POT: "PotCoin",
  HPT: "Huobi Pool Token",
  HELMET: "Helmet.insure",
  ZEFU: "Zenfuse",
  ELEC: "Electrify.Asia",
  GMAT: "GoWithMi",
  DOSE: "DOSE",
  MIBR: "MIBR Fan Token",
  WPR: "WePower",
  LZ: "LaunchZone",
  HGET: "Hedget",
  STEP: "Step Finance",
  SNET: "Snetwork",
  FINE: "Refinable",
  EZ: "EasyFi",
  EBST: "eBoost",
  CDT: "CheckDot",
  SAM: "Samsunspor Fan Token",
  HYC: "HYCON",
  SKM: "Skrumble Network",
  AID: "AidCoin",
  PVU: "Plant Vs Undead",
  STND: "Standard Protocol",
  PETS: "MicroPets",
  EVX: "Everex",
  DDOS: "disBalancer",
  AIRT: "AirNFTs",
  ING: "Infinity Games",
  JRT: "Jarvis Network",
  VSO: "Verso",
  DWEB: "DecentraWeb",
  TYPE: "Typerium",
  LDOGE: "LiteDoge",
  CRX: "CryptEx",
  LML: "Link Machine Learning",
  "2CRZ": "2crazyNFT",
  SUB: "Subme",
  ALL: "Alliance Fan Token",
  DOP: "Drops Ownership Power",
  VDL: "Vidulum",
  VISION: "VisionGame",
  MVP: "Merculet",
  DMG: "DMM: Governance",
  SKB: "Sakura Bloom",
  BOX: "ContentBox",
  SWACE: "Swace",
  SWT: "Swarm City",
  YETIC: "YetiCoin",
  DNXC: "DinoX",
  BANK: "Float Protocol (Bank)",
  BLKC: "BlackHat",
  PFL: "Professional Fighters League Fan Token",
  BZNT: "Bezant",
  PAK: "Pakcoin",
  MASS: "Massnet",
  PIN: "Public Index Network",
  RET: "RealTract",
  DRC: "Dracula Token",
  PAINT: "MurAll",
  EVED: "Evedo",
  RATING: "DPRating",
  INXT: "Internxt",
  TRC: "Terracoin",
  $ANRX: "AnRKey X",
  TH: "Team Heretics Fan Token",
  OST: "OST",
  PACOCA: "Pacoca",
  MOTA: "MotaCoin",
  TCH: "Thore Cash",
  SETH: "Sether",
  LEVL: "Levolution",
  EOSDAC: "eosDAC",
  WTN: "Waletoken",
  CHEEMS: "Cheems",
  DXL: "Dexlab",
  CANDY: "TripCandy",
  NCash: "Nitro Network",
  SFX: "Safex Cash",
  DZG: "Dinamo Zagreb Fan Token",
  GDAO: "Governor DAO",
  GEO: "GeoDB",
  BBP: "BiblePay",
  KTON: "Darwinia Commitment Token",
  NANJ: "NANJCOIN",
  UIP: "UnlimitedIP",
  BLINK: "BLink",
  CRW: "Crown",
  KANGAL: "Kangal",
  FSW: "Falconswap",
  CAI: "Club Atletico Independiente",
  SOLX: "Soldex",
  NAVI: "Natus Vincere Fan Token",
  DOWS: "Shadows",
  CVR: "CoverCompared",
  MAKI: "MakiSwap",
  VNLA: "Vanilla Network",
  DHV: "DeHive",
  SHOPX: "SHOPX",
  BCPT: "Blockmason Credit Protocol",
  YEE: "YEE",
  "1EARTH": "EarthFund",
  BRZE: "Breezecoin",
  CERES: "Ceres",
  NEXT: "ShopNEXT",
  KART: "Dragon Kart",
  WISH: "MyWish",
  TKS: "Tokes",
  COOK: "Cook Finance",
  VIG: "VIG",
  COR: "Coreto",
  "YF-DAI": "YFDAI.FINANCE",
  RENDOGE: "renDOGE",
  WNDR: "Wonderman Nation",
  APY: "APY.Finance",
  HUSL: "The HUSL",
  XIO: "Blockzero Labs",
  TYC: "Tycoon",
  RINGX: "RING X PLATFORM",
  AG8: "AtromG8",
  YOP: "Yield Optimization Platform & Protocol",
  XMX: "XMax",
  LEG: "Legia Warsaw Fan Token",
  CAPP: "Cappasity",
  GOF: "Golff",
  XPNET: "XP NETWORK",
  SWM: "Swarm",
  ASTRO: "AstroSwap",
  PASS: "Blockpass",
  WAB: "WABnetwork",
  NINO: "Ninneko",
  OIN: "OIN Finance",
  SNB: "SynchroBitcoin",
  BXY: "Beaxy",
  RNT: "OneRoot Network",
  MANNA: "Manna",
  ODIN: "ODIN PROTOCOL",
  TIDAL: "Tidal Finance",
  VLXPAD: "VelasPad",
  UUU: "U Network",
  UCA: "UCA Coin",
  HBX: "HashBX",
  EQL: "Equal",
  SDT: "Stake DAO",
  HYDRO: "Hydro",
  MAT: "My Master War",
  LFW: "Linked Finance World",
  IDEA: "Ideaology",
  N1: "NFTify",
  CYMT: "CyberMusic",
  FCL: "Fractal",
  IRD: "Iridium",
  GLINT: "BeamSwap",
  FUEL: "Etherparty",
  DVP: "Decentralized Vulnerability Platform",
  TTN: "Titan Coin",
  BAC: "Basis Cash",
  XMY: "Myriad",
  MNTP: "GoldMint",
  MDS: "MediShares",
  SIGN: "Signature Chain",
  FBX: "Finance Blocks",
  INK: "Ink",
  FNDZ: "FNDZ",
  LFG: "Gamerse",
  MBC: "MicroBitcoin",
  SPWN: "Bitspawn",
  NOV: "Novara Calcio Fan Token",
  L2: "Leverj Gluon",
  FIU: "beFITTER",
  FOUR: "4THPILLAR TECHNOLOGIES",
  LEAD: "Lead Wallet",
  ZNT: "Zenswap Network Token",
  SAKE: "SakeToken",
  COT: "CoTrader",
  BUZZ: "BUZZCoin",
  DATP: "Decentralized Asset Trading Platform",
  FOTA: "FOTA - Fight Of The Ages",
  TCP: "The Crypto Prophecies",
  CNTM: "Connectome",
  CORGIB: "The Corgi of PolkaBridge",
  SCC: "SiaCashCoin",
  OLXA: "OLXA",
  FTX: "FintruX Network",
  PXG: "PlayGame",
  TRST: "WeTrust",
  MOTO: "Motocoin",
  ZEBI: "Zebi Token",
  QBT: "Qbao",
  FREED: "Freedomcoin",
  POLI: "Polinate",
  ZORA: "Zoracles",
  LUC: "Lucretius",
  ARQ: "Arqma",
  TUBE: "BitTube",
  AXIS: "Axis DeFi",
  FORM: "Formation Fi",
  VIT: "Team Vitality Fan Token",
  APN: "Apron Network",
  BNU: "ByteNext",
  BOMB: "BOMB",
  NETKO: "Netko",
  SAO: "Sator",
  IHT: "IHT Real Estate Protocol",
  LEPA: "Lepasa",
  ROYA: "Royale Finance",
  FLIXX: "Flixxo",
  DOPE: "DopeCoin",
  ADD: "Add.xyz",
  BLUE: "Blue Protocol",
  PWR: "PWR Coin",
  FTI: "FansTime",
  ORION: "Orion Money",
  XST: "Stealth",
  ROCKI: "ROCKI",
  NRP: "Neural Protocol",
  KURT: "Kurrent",
  XRC: "xRhodium",
  NTK: "Neurotoken",
  REM: "Remme",
  MODX: "MODEL-X-coin",
  BANCA: "Banca",
  AUC: "Auctus",
  SHARE: "Seigniorage Shares",
  DINO: "DinoSwap",
  IXT: "IXT",
  ETGP: "Ethereum Gold Project",
  ROUSH: "Roush Fenway Racing Fan Token",
  SSP: "Smartshare",
  MPAY: "MenaPay",
  A: "Alpha Token",
  BPS: "BitcoinPoS",
  SINS: "SafeInsure",
  BITG: "Bitcoin Green",
  TROLL: "Trollcoin",
  DRT: "DomRaider",
  GRFT: "Graft",
  HAVY: "Havy",
  VOX: "Vox.Finance",
  BNTY: "Bounty0x",
  LTHN: "Lethean",
  MES: "MesChain",
  XNV: "Nerva",
  BLU: "BlueCoin",
  IFT: "InvestFeed",
  BCUG: "Blockchain Cuties Universe Governance",
  CREO: "Creo Engine",
  NOR: "Noir",
  TELOS: "Teloscoin",
  BITS: "Bitstar",
  ASKO: "ASKO",
  MOMA: "Mochi Market",
  HTZ: "Hertz Network",
  ELAND: "Etherland",
  EOST: "EOS TRUST",
  CTL: "Citadel",
  CRE8: "Creaticles",
  GENESIS: "Genesis Worlds",
  ENT: "Eternity",
  ROAD: "Yellow Road",
  YIELD: "Yield Protocol",
  "2GIVE": "2GIVE",
  APC: "Alpha Coin",
  ARCO: "AquariusCoin",
  KOBO: "Kobocoin",
  TSL: "Energo",
  SWING: "Swing",
  AOK: "AOK",
  X42: "x42 Protocol",
  CTRT: "Cryptrust",
  CNB: "Coinsbit Token",
  AMN: "Amon",
  BRY: "Berry Data",
  NUX: "Peanut",
  KWT: "Kawaii Islands",
  ETNA: "ETNA Network",
  POSW: "PoSW Coin",
  KDG: "Kingdom Game 4.0",
  HSC: "HashCoin",
  VDR: "Vodra",
  WQT: "WorkQuest Token",
  MSR: "Masari",
  EVY: "EveryCoin",
  ESH: "Switch",
  GS: "Genesis Shards",
  MOBIC: "Mobility Coin",
  BID: "DeFi Bids",
  BTA: "Bata",
  PVT: "Pivot Token",
  IOEN: "Internet of Energy Network",
  WFX: "Webflix Token",
  PINK: "Pinkcoin",
  BBS: "BBSCoin",
  CHX: "WeOwn",
  MILK2: "Spaceswap MILK2",
  OSWAP: "OpenSwap",
  SGT: "SharedStake",
  TERA: "TERA",
  SHAKE: "Spaceswap SHAKE",
  NYZO: "Nyzo",
  ZSC: "Zeusshield",
  ZNZ: "ZENZO",
  EXP: "Expanse",
  COB: "Cobinhood",
  JADE: "Jade Currency",
  MYRA: "Mytheria",
  CJ: "Cryptojacks",
  AIX: "Aigang",
  FRC: "Freicoin",
  ORAO: "ORAO Network",
  N8V: "NativeCoin",
  ALN: "Aluna.Social",
  DBET: "DecentBet",
  ZUM: "ZumCoin",
  AZUKI: "Azuki",
  SHND: "StrongHands",
  KNDC: "KanadeCoin",
  TAG: "TagCoin",
  MIB: "MIB Coin",
  TOTO: "Tourist Token",
  DLT: "Agrello",
  KEYFI: "KeyFi",
  XAS: "Asch",
  UBEX: "Ubex",
  DONUT: "Donut",
  GEM: "Gems",
  SHDW: "Shadow Token",
  POE: "Po.et",
  SWG: "Swirge",
  AAC: "Double-A Chain",
  GUM: "Gourmet Galaxy",
  KNIGHT: "Forest Knight",
  CHEESE: "Cheesecoin",
  ARGON: "Argon",
  CLS: "Coldstack",
  MYB: "MyBit",
  GOLD: "Golden Goose",
  BYN: "Beyondfi",
  DDK: "DDKoin",
  PKG: "PKG Token",
  COSM: "Cosmo Coin",
  YVS: "YVS.Finance",
  EBA: "Elpis Battle",
  SENC: "Sentinel Chain",
  RAGE: "Rage Fan",
  RBT: "Rimbit",
  INFI: "Insured Finance",
  PHR: "Phore",
  NFY: "Non-Fungible Yearn",
  KIMCHI: "KIMCHI.finance",
  NSURE: "Nsure.Network",
  BUNI: "Bunicorn",
  ZCR: "ZCore",
  TCS: "Timechain Swap Token",
  INSN: "InsaneCoin",
  SCONEX: "Sportcash One",
  ELAMA: "Elamachain",
  IG: "IGToken",
  ION: "ION",
  INX: "Insight Protocol",
  SYP: "Sypool",
  SNN: "SeChain",
  CATT: "Catex Token",
  CRACE: "Coinracer",
  SNOB: "Snowball",
  BREW: "CafeSwap Token",
  FOC: "TheForce Trade",
  XWP: "Swap",
  BTB: "BitBall",
  eYe: "MEDIA EYE NFT Portal",
  BERRY: "Berry",
  AUX: "Auxilium",
  CLX: "Celeum",
  SHOE: "ShoeFy",
  PYRO: "PYRO Network",
  FIC: "Filecash",
  ATMOS: "Atmos",
  SHIELD: "Shield Protocol",
  NTRN: "Neutron",
  UFARM: "UniFarm",
  ARGO: "ArGo",
  ENG: "Enigma",
  SVX: "Savix",
  SFUEL: "SparkPoint Fuel",
  SKYRIM: "Skyrim Finance",
  VIKKY: "VikkyToken",
  PAYB: "Paybswap",
  CHART: "ChartEx",
  CTT: "Castweet",
  DCNTR: "Decentrahub Coin",
  DYT: "DoYourTip",
  IPL: "VouchForMe",
  DOM: "Ancient Kingdom",
  MOJO: "MojoCoin",
  JET: "Jetcoin",
  MEL: "MELX",
  WRC: "Worldcore",
  SNRG: "Synergy",
  XBP: "BlitzPick",
  BOLI: "Bolivarcoin",
  LUN: "Lunyr",
  RGP: "Rigel Protocol",
  UPX: "uPlexa",
  FTXT: "FUTURAX",
  BC: "Bitcoin Confidential",
  COLL: "Collateral Pay",
  SNY: "Synthetify",
  WOW: "WOWswap",
  DOKI: "Doki Doki Finance",
  COVA: "COVA",
  CNN: "Content Neutrality Network",
  PHT: "Phoneum",
  XPTX: "PlatinumBAR",
  TANGO: "keyTango",
  AMM: "MicroMoney",
  SCHO: "Scholarship Coin",
  PLAT: "BitGuild PLAT",
  MARTK: "Martkist",
  EVIL: "Evil Coin",
  GCN: "GCN Coin",
  TZC: "TrezarCoin",
  ADI: "Aditus",
  WARP: "Warp Finance",
  XCT: "Citadel.one",
  KFX: "KnoxFS",
  HEROEGG: "HeroFi",
  NVC: "Novacoin",
  SKIN: "SkinCoin",
  TAP: "Tapx",
  NDX: "Indexed Finance",
  TOTM: "TotemFi",
  CBIX: "Cubiex",
  EKT: "EDUCare",
  CHRP: "Chirpley",
  YTN: "YENTEN",
  OGO: "Origo",
  ICR: "InterCrone",
  BUNNY: "Pancake Bunny",
  MCC: "MultiCoinCasino",
  PRARE: "POLKARARE",
  UP: "UpToken",
  RBIES: "Rubies",
  PLURA: "PluraCoin",
  VEKTOR: "VEKTOR",
  MAS: "MidasProtocol",
  DOGES: "Dogeswap",
  AMA: "AMATEN",
  PRIX: "Privatix",
  HTD: "HeroesTD",
  EGEM: "EtherGem",
  ART: "Maecenas",
  PEOS: "pEOS",
  ERO: "Eroscoin",
  PHX: "Phoenix Token",
  VIVID: "Vivid Coin",
  BLTG: "Block-Logic",
  MND: "Mind Music",
  KOI: "Koi Network",
  STEEP: "SteepCoin",
  ADM: "ADAMANT Messenger",
  ELY: "Elysian",
  RITO: "Ritocoin",
  MMO: "MMOCoin",
  GSAIL: "SolanaSail Governance Token",
  LYRA: "Scrypta",
  PYM: "Playermon",
  BTW: "BitWhite",
  "2LC": "2local",
  WSPP: "Wolf Safe Poor People (Polygon)",
  ATB: "ATBCoin",
  SMTY: "Smoothy",
  DTRC: "Datarius Credit",
  LUX: "LUXCoin",
  XDOGE: "ClassicDoge",
  STAR: "Starbase",
  ALP: "CoinAlpha",
  DONU: "Donu",
  FBN: "Fivebalance",
  UNIFY: "Unify",
  CNS: "Centric Swap",
  BTZC: "BeatzCoin",
  OPAL: "Opal",
  GFX: "GamyFi Platform",
  SPK: "SparksPay",
  EVC: "EventChain",
  WCC: "WinCash",
  XPA: "XPA",
  UNIT: "Universal Currency",
  ARAW: "ARAW",
  ISA: "Islander",
  BERN: "BERNcash",
  BURN: "Blockburn",
  GB: "GoldBlocks",
  FLOT: "Fire Lotto",
  CORX: "CorionX",
  DFT: "DraftCoin",
  NNI: "NeoNomad",
  SHMN: "StrongHands Masternode",
  ELTCOIN: "ELTCOIN",
  EVN: "EvenCoin",
  CUR: "Curio",
  VIDZ: "PureVidz",
  BNF: "BonFi",
  XRA: "Ratecoin",
  NSD: "Nasdacoin",
  GXT: "Gem Exchange and Trading",
  EXE: "8X8 PROTOCOL",
  XPY: "PayCoin",
  AFEN: "AFEN Blockchain Network",
  NEVA: "NevaCoin",
  ZET: "Zetacoin",
  ZUKI: "Zuki Moba",
  SPD: "SPINDLE",
  UBN: "Ubricoin",
  CCN: "CustomContractNetwork",
  KOMBAT: "Crypto Kombat",
  SAMU: "Samusky",
  DDL: "DeFi Degen Land",
  NTR: "Netrum",
  RPZX: "Rapidz",
  LITHO: "Lithosphere",
  POST: "PostCoin",
  ARO: "Arionum",
  YOC: "Yocoin",
  KUV: "Kuverit",
  ONX: "Onix",
  ICOB: "ICOBID",
  GCR: "Global Currency Reserve",
  RUP: "Rupee",
  ARCT: "ArbitrageCT",
  CSPN: "Crypto Sports Network",
  GCC: "GuccioneCoin",
  BITC: "BitCash",
  MONK: "MONK",
  MAY: "Theresa May Coin",
  ADZ: "Adzcoin",
  CREDIT: "CREDIT",
  VOTE: "Agora",
  MORE: "More Coin",
  ECO: "Ormeus Ecosystem",
  ASAFE: "AllSafe",
  FNB: "FNB Protocol",
  ALLBI: "ALL BEST ICO",
  AKA: "Akroma",
  KFT: "Knit Finance",
  LMT: "Lympo Market Token",
  TNS: "Transcodium",
  RENA: "Warena",
  DGTX: "Digitex",
  DSR: "Desire",
  NFXC: "NFX Coin",
  TBX: "Tokenbox",
  TAJ: "TajCoin",
  MOWA: "Moniwar",
  ETHPLO: "ETHplode",
  XGT: "Xion Finance",
  AXE: "Axe",
  FRST: "FirstCoin",
  TDP: "TrueDeck",
  XDNA: "XDNA",
  IMG: "ImageCoin",
  ALPHR: "Alphr finance",
  BECN: "Beacon",
  KNT: "Knekted",
  "1MIL": "1MillionNFTs",
  C2: "Coin2.1",
  CNT: "Centurion",
  RASKO: "rASKO",
  AREPA: "Arepacoin",
  KSEED: "Kush Finance",
  ORMEUS: "Ormeus Coin",
  ESCE: "Escroco Emerald",
  DCTO: "Decentralized Crypto Token",
  "1UP": "Uptrennd",
  BSD: "BitSend",
  RVT: "Rivetz",
  GLT: "GlobalToken",
  GOSS: "Gossip Coin",
  ABX: "Arbidex",
  BEET: "Beetlecoin",
  EUC: "Eurocoin",
  BTAD: "Bitcoin Adult",
  VAULT: "VAULT",
  BOUTS: "BoutsPro",
  KWS: "Knight War - The Holy Trio",
  DGC: "Digitalcoin",
  MEDIC: "MedicCoin",
  ELET: "Elementeum",
  GBX: "GoByte",
  BSC: "BowsCoin",
  SHVR: "Shivers",
  PNX: "Phantomx",
  FGC: "FantasyGold",
  HB: "HeartBout",
  INNBC: "Innovative Bioresearch Coin",
  HERON: "Heron Asia",
  CBM: "CryptoBonusMiles",
  AMS: "AmsterdamCoin",
  SACT: "srnArt Gallery",
  EDRC: "EDRCoin",
  BELA: "Bela",
  XCO: "X-Coin",
  FUZZ: "FuzzBalls",
  CCO: "Ccore",
  HERB: "Herbalist Token",
  CDL: "CoinDeal Token",
  GSR: "GeyserCoin",
  MST: "MustangCoin",
  START: "Startcoin",
  XUEZ: "Xuez",
  NAVY: "BoatPilot Token",
  EVT: "EveriToken",
  BLOC: "BLOC.MONEY",
  DOE: "Dogs Of Elon",
  TM2: "TRAXIA",
  GAJ: "Gaj Finance",
  BSL: "BSClaunch",
  BXC: "Bitcoin Classic",
  TWIN: "Twinci",
  NASH: "NeoWorld Cash",
  STAC: "StarterCoin",
  LUS: "Luna Rush",
  QUAN: "Quantis Network",
  DTC: "Datacoin",
  XBTC21: "Bitcoin 21",
  LCMS: "LCMS",
  XGS: "GenesisX",
  PKB: "ParkByte",
  AIM: "ModiHost",
  KALA: "Kalata",
  CF: "Californium",
  RHT: "Reward Hunters Token",
  CREVA: "CrevaCoin",
  STPL: "Stream Protocol",
  EKO: "EchoLink",
  XBI: "Bitcoin Incognito",
  ZINC: "ZINC",
  BON: "Bonpay",
  SPR: "SpreadCoin",
  KUN: "KUN",
  SONG: "SongCoin",
  SFCP: "SF Capital",
  DVC: "DragonVein",
  SCRIV: "SCRIV NETWORK",
  PYN: "PAYCENT",
  ALLOY: "HyperAlloy",
  CAB: "Cabbage",
  IC: "Ignition",
  IBTC: "iBTC",
  JS: "JavaScript Token",
  LTCR: "Litecred",
  QRT: "Qrkita Token",
  FUZE: "FUZE Token",
  STREAM: "Streamit Coin",
  QBC: "Quebecoin",
  KWIK: "Kwikswap Protocol",
  ACOIN: "Acoin",
  ROOM: "OptionRoom",
  SFG: "S.Finance",
  TVNT: "TravelNote",
  HELP: "GoHelpFund",
  KKO: "Kineko",
  COAL: "BitCoal",
  PXI: "Prime-XI",
  SCS: "SpeedCash",
  ARB: "ARbit",
  PAYX: "Paypex",
  ICON: "Iconic",
  VLT: "Veltor",
  SET: "Save Environment Token",
  DYNMT: "Dynamite",
  ZYD: "Zayedcoin",
  VEC2: "VectorAI",
  CXT: "Coinonat",
  PLNC: "PLNcoin",
  EXO: "Exosis",
  LTK: "LitecoinToken",
  IMS: "Independent Money System",
  GPKR: "Gold Poker",
  HVCO: "High Voltage",
  WTF: "Waterfall DeFi",
  XAP: "Apollon",
  KEMA: "Kemacoin",
  SHB: "SkyHub Coin",
  GDR: "Guider",
  IBANK: "iBank",
  JOINT: "Joint Ventures",
  PYRK: "Pyrk",
  XGM: "Defis",
  SCAP: "SafeCapital",
  TCAT: "The Currency Analytics",
  MATE: "Mate",
  CRM: "Cream",
  MCPC: "Mobile Crypto Pay Coin",
  MERI: "Merebel",
  XOV: "XOVBank",
  CNNC: "Cannation",
  FNX: "FinNexus",
  NOTE: "Note",
  CRDT: "CRDT",
  SWC: "Scanetchain",
  LTCU: "LiteCoin Ultra",
  SOCC: "SocialCoin",
  ROFI: "HeroFi (ROFI)",
  "CBIX-P": "Cubiex Power",
  REW: "Rewardiqa",
  RIGEL: "Rigel Finance",
  CYL: "Crystal Token",
  SANDG: "Save and Gain",
  SEFA: "Mesefa",
  DASHG: "Dash Green",
  ELD: "Electrum Dark",
  WBB: "Wild Beast Block",
  ARGUS: "Argus",
  KZC: "KZ Cash",
  VLS: "Veles",
  CONX: "Concoin",
  DIN: "Dinero",
  PONZI: "PonziCoin",
  BLIZZ: "Blizzard Network",
  FLL: "Feellike",
  IRA: "Diligence",
  TREX: "Trexcoin",
  STO: "Storeum",
  AAA: "Abulaba",
  KTS: "Klimatas",
  ARNX: "Aeron",
  ECU: "ECOSC",
  GMC: "GokuMarket Credit",
  NBXC: "Nibble",
  CPAN: "CryptoPlanes",
  RNBW: "HaloDAO",
  YFFII: "YFFII Finance",
  MFTU: "Mainstream For The Underground",
  WETH: "WETH",
  PCI: "Paycoin",
  "BB-A-USDT": "Balancer Boosted Aave USDT",
  "BB-A-USDC": "Balancer Boosted Aave USDC",
  WCANTO: "Wrapped CANTO",
  WMATIC: "Wrapped Matic",
  FRP: "Fame Reward Plus",
  BTCA: "BITCOIN ADDITIONAL",
  WAVAX: "Wrapped AVAX",
  GGP: "Geegoopuzzle",
  WSTETH: "Lido wstETH",
  HIFI: "Hifi Finance",
  BPTC: "Business Platform Tomato Coin",
  XT: "XT.com Token",
  CBETH: "Coinbase Wrapped Staked ETH",
  STABLZ: "Stablz",
  RDNT: "Radiant Capital",
  DMTR: "Dimitra",
  WFTM: "Wrapped Fantom",
  XTUSD: "XT Stablecoin XTUSD",
  GNS: "Gains Network",
  FLR: "Flare",
  CVXCRV: "Convex CRV",
  PSI: "TridentDAO",
  DOME: "Everdome",
  BETH: "Beacon ETH",
  TBCC: "TBCC",
  X2Y2: "X2Y2",
  CUSDC: "Compound USD Coin",
  BONK: "Bonk",
  UT: "Fantaverse",
  AUDT: "Australian Dollar Token",
  CDAI: "Compound Dai",
  stMATIC: "Lido Staked Matic",
  VELA: "Vela Token",
  GRAIL: "Camelot Token",
  USDCE: "USD Coin Bridged",
  BCB: "Blockchain Bets",
  ASTO: "Altered State Token",
  CPC: "CPCoin",
  GRV: "Grove Coin",
  SPRT: "Sportium",
  SHINJA: "Shibnobi(New)",
  "BTC.b": "Bitcoin Avalanche Bridged",
  FXC: "FUTUREXCRYPTO",
  MUSICAI: "MusicAI",
  SOON: "Soonaverse",
  FILDA: "Filda",
  JPEG: "JPEG'd",
  CNX: "Cryptonex",
  ZEDXION: "ZEDXION",
  PLEX: "MinePlex",
  FOLD: "Manifold Finance",
  SQUAD: "Superpower Squad",
  GALAXY: "Galaxy Coin",
  GEAR: "Gearbox Protocol",
  P2PS: "P2P Solutions foundation",
  PRIMAL: "PRIMAL",
  SWISE: "StakeWise",
  BBC: "BULL BTC CLUB",
  OKT: "OKC Token",
  RETH: "Rocket Pool ETH",
  MULTI: "Multichain",
  NFTN: "NFTNetwork",
  FLAME: "FireStarter",
  OAS: "Oasys",
  XETA: "XANA",
  HBD: "Hive Dollar",
  hiBAYC: "hiBAYC",
  SIENNA: "Sienna",
};
